name: Run Inventory Script

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    # Only one working directory setting here
    defaults:
      run:
        working-directory: mongodb_backend_project

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file from GitHub Secret
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env

    - name: Debug .env file (optional)
      run: cat .env

    - name: Run Inventory Script
      run: python main.py