name: Run Inventory Script

on:
  workflow_dispatch:  # Allows you to manually trigger it

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file from GitHub Secret
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env

    - name: Run Inventory Script with .env loaded
      run: |
        set -a
        source .env
        set +a
        python main.py